(ns platinum-rift.constants)

(def pod-cost 20)
(def starting-plat 200)
(def debug true)
(def starting-plat 200)
(def num-nodes 154)
(def standard-radius 3)
(def max-res 200)
(def max-inc 6)
(def max-fight-loop 3)
